CREATE TABLE IF NOT EXISTS coin_info
(
    id        VARCHAR(50) PRIMARY KEY,
    symbol    VARCHAR(10)  NOT NULL,
    name      VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    latestAt  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "order"   INTEGER   DEFAULT 1
);

CREATE TABLE IF NOT EXISTS coin_ohlc
(
    id        SERIAL PRIMARY KEY,
    idCoin    VARCHAR(50)     NOT NULL,
    time      BIGINT          NOT NULL,
    open      NUMERIC(20, 10) NOT NULL,
    high      NUMERIC(20, 10) NOT NULL,
    low       NUMERIC(20, 10) NOT NULL,
    close     NUMERIC(20, 10) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (idCoin, time),
    FOREIGN KEY (idCoin) REFERENCES coin_info (id)
);
CREATE TABLE IF NOT EXISTS coin_price
(
    id        SERIAL PRIMARY KEY,
    idCoin    VARCHAR(50)     NOT NULL,
    time      BIGINT          NOT NULL,
    price     NUMERIC(20, 10) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (idCoin, time),
    FOREIGN KEY (idCoin) REFERENCES coin_info (id)
);

INSERT INTO coin_info (id, symbol, name)
VALUES ('ada-the-dog', 'ada', 'ADA the Dog'),
       ('algorand', 'algo', 'Algorand'),
       ('avalanche-2', 'avax', 'Avalanche'),
       ('avalanche-wormhole', 'avax', 'Avalanche (Wormhole)'),
       ('beam-bridged-avax-beam', 'avax', 'Beam Bridged AVAX (Beam)'),
       ('binancecoin', 'bnb', 'BNB'),
       ('binance-coin-wormhole', 'bnb', 'Binance Coin (Wormhole)'),
       ('binance-peg-avalanche', 'avax', 'Binance-Peg Avalanche'),
       ('binance-peg-bitcoin-cash', 'bch', 'Binance-Peg Bitcoin Cash'),
       ('binance-peg-cardano', 'ada', 'Binance-Peg Cardano'),
       ('binance-peg-dogecoin', 'doge', 'Binance-Peg Dogecoin'),
       ('binance-peg-eos', 'eos', 'Binance-Peg EOS'),
       ('binance-peg-filecoin', 'fil', 'Binance-Peg Filecoin'),
       ('binance-peg-litecoin', 'ltc', 'Binance-Peg Litecoin'),
       ('binance-peg-polkadot', 'dot', 'Binance-Peg Polkadot'),
       ('binance-peg-xrp', 'xrp', 'Binance-Peg XRP'),
       ('bitcoin', 'btc', 'Bitcoin'),
       ('bitcoin-cash', 'bch', 'Bitcoin Cash'),
       ('blackrocktradingcurrency', 'btc', 'BlackrockTradingCurrency'),
       ('bridged-binance-peg-ethereum-opbnb', 'eth', 'Bridged Binance-Peg Ethereum (opBNB)'),
       ('bridged-dai-stablecoin-linea', 'dai', 'Bridged Dai Stablecoin (Linea)'),
       ('bridged-dai-stablecoin-manta-pacific', 'dai', 'Bridged Dai Stablecoin (Manta Pacific)'),
       ('bridged-dai-starkgate', 'dai', 'Bridged Dai Stablecoin (StarkGate)'),
       ('bridged-wrapped-ether-starkgate', 'eth', 'Bridged Ether (StarkGate)'),
       ('cardano', 'ada', 'Cardano'),
       ('chainlink', 'link', 'Chainlink'),
       ('cosmos', 'atom', 'Cosmos Hub'),
       ('dai', 'dai', 'Dai'),
       ('dai-pulsechain', 'dai', 'DAI (PulseChain)'),
       ('dogecoin', 'doge', 'Dogecoin'),
       ('doge-on-pulsechain', 'doge', 'Doge on Pulsechain'),
       ('dogezilla-ai', 'dai', 'DogeZilla Ai'),
       ('eos', 'eos', 'EOS'),
       ('ethereum', 'eth', 'Ethereum'),
       ('ethereum-classic', 'etc', 'Ethereum Classic'),
       ('ethereum-wormhole', 'eth', 'Ethereum (Wormhole)'),
       ('filecoin', 'fil', 'Filecoin'),
       ('harrypotterobamapacman8inu', 'xrp', 'HarryPotterObamaPacMan8Inu'),
       ('heco-peg-bnb', 'bnb', 'Heco-Peg Binance Coin'),
       ('heco-peg-xrp', 'xrp', 'Heco-Peg XRP'),
       ('immutable-zkevm-bridged-eth', 'eth', 'Immutable zkEVM Bridged ETH'),
       ('internet-computer', 'icp', 'Internet Computer'),
       ('litecoin', 'ltc', 'Litecoin'),
       ('lxly-bridged-dai-astar-zkevm', 'dai', 'LxLy Bridged DAI (Astar zkEVM)'),
       ('matic-network', 'matic', 'Polygon'),
       ('monero', 'xmr', 'Monero'),
       ('neo', 'neo', 'NEO'),
       ('oec-binance-coin', 'bnb', 'OEC Binance Coin'),
       ('playground-waves-floor-index', 'waves', 'Playground Waves Floor Index'),
       ('polkadot', 'dot', 'Polkadot'),
       ('ripple', 'xrp', 'XRP'),
       ('ronweasleytrumptoadn64inu', 'bnb', 'RonWeasleyTrumpToadN64Inu'),
       ('solana', 'sol', 'Solana'),
       ('sol-wormhole', 'sol', 'SOL (Wormhole)'),
       ('stellar', 'xlm', 'Stellar'),
       ('terra-luna-2', 'luna', 'Terra'),
       ('tezos', 'xtz', 'Tezos'),
       ('the-infinite-garden', 'eth', 'The Infinite Garden'),
       ('theta-token', 'theta', 'Theta Network'),
       ('tron', 'trx', 'TRON'),
       ('tron-bsc', 'trx', 'TRON (BSC)'),
       ('unicorn-token', 'uni', 'UNICORN'),
       ('unilapse', 'uni', 'UNILAPSE'),
       ('uniswap', 'uni', 'Uniswap'),
       ('uniswap-wormhole', 'uni', 'Uniswap (Wormhole)'),
       ('uni-the-wonder-dog', 'uni', 'Uni the Wonder Dog'),
       ('vechain', 'vet', 'VeChain'),
       ('warioxrpdumbledoreyugioh69inu', 'xrp', 'WarioXRPDumbledoreYugioh69Inu'),
       ('waves', 'waves', 'Waves'),
       ('wrapped-solana', 'sol', 'Wrapped Solana'),
       ('xcdot', 'dot', 'xcDOT');
