definitions:
  handlers.CoinOHLCResponse:
    properties:
      close:
        type: number
      createdAt:
        type: string
      high:
        type: number
      id:
        type: integer
      idCoin:
        type: string
      low:
        type: number
      open:
        type: number
      time:
        type: integer
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /get-histories:
    get:
      consumes:
      - application/json
      description: get historical open, high, low, and close data for a coin
      parameters:
      - description: Coin Symbol
        in: query
        name: symbol
        required: true
        type: string
      - description: Start Date
        format: date
        in: query
        name: start_date
        required: true
        type: string
      - description: End Date
        format: date
        in: query
        name: end_date
        required: true
        type: string
      - description: Data period (30M, 1H, 1D)
        in: query
        name: period
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.CoinOHLCResponse'
            type: array
      summary: Get historical OHLC data for a coin
      tags:
      - coin
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of the API
      tags:
      - healthcheck
swagger: "2.0"
